/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedFechamentosIndexRouteImport } from './routes/_authenticated/fechamentos.index'
import { Route as AuthenticatedFechamentosIdRouteImport } from './routes/_authenticated/fechamentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFechamentosIndexRoute =
  AuthenticatedFechamentosIndexRouteImport.update({
    id: '/fechamentos/',
    path: '/fechamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFechamentosIdRoute =
  AuthenticatedFechamentosIdRouteImport.update({
    id: '/fechamentos/$id',
    path: '/fechamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/fechamentos/': typeof AuthenticatedFechamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/fechamentos': typeof AuthenticatedFechamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/fechamentos/$id': typeof AuthenticatedFechamentosIdRoute
  '/_authenticated/fechamentos/': typeof AuthenticatedFechamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fechamento'
    | '/importar'
    | '/usuarios'
    | '/fechamentos/$id'
    | '/fechamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fechamento'
    | '/importar'
    | '/usuarios'
    | '/fechamentos/$id'
    | '/fechamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fechamento'
    | '/_authenticated/importar'
    | '/_authenticated/usuarios'
    | '/_authenticated/fechamentos/$id'
    | '/_authenticated/fechamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamentos/': {
      id: '/_authenticated/fechamentos/'
      path: '/fechamentos'
      fullPath: '/fechamentos/'
      preLoaderRoute: typeof AuthenticatedFechamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamentos/$id': {
      id: '/_authenticated/fechamentos/$id'
      path: '/fechamentos/$id'
      fullPath: '/fechamentos/$id'
      preLoaderRoute: typeof AuthenticatedFechamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedFechamentosIdRoute: typeof AuthenticatedFechamentosIdRoute
  AuthenticatedFechamentosIndexRoute: typeof AuthenticatedFechamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedFechamentosIdRoute: AuthenticatedFechamentosIdRoute,
  AuthenticatedFechamentosIndexRoute: AuthenticatedFechamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
